void rightRotate( TreeNode *x, TreeNode **root );
void  leftRotate( TreeNode *x, TreeNode **root );
void InsertTreeNode( TreeNode **root, Interval *interval );
void DeleteNode( TreeNode **root, Interval *interval );
TreeNode* allocateTreeNode( TreeNode **parent, Interval *interval, bool color, int left_root_right );
void printInorder( TreeNode *node );
TreeNode* inorderSuccessor( TreeNode *node );
bool validateBST(TreeNode* node, TreeNode* prev);
bool isValidBST(TreeNode* root);
bool isBalanced(TreeNode *root);
void print2D( TreeNode* root);
bool isLeftChild( TreeNode * node, char *fileName, int line );
TreeNode* searchInterval( TreeNode *root, Interval *interval, ListNode **listNode );
ListNode *SearchListNode( ListNode *head, int key );
void AddListNode( ListNode **head, int key );
void DeleteListNode( ListNode *deleteNode );
void FreeList( ListNode *head );
